[phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[phases.install]
cmds = ["python3.11 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
